### ISSUE TITLE
For Flutter Web: AssetNotFoundException: realspaceweb|lib/main_prod_web_entrypoint.ddc.js

### ISSUE THREAD

**Issue by anastasiyakisel** [smkhalsa/gql_client#2]
Following the instruction, for Flutter Web getting the below error. Suppose, this is because gql_build is not yet available for Flutter Web. Otherwise, please assist : 

Launching lib/main.dart on Chrome in debug mode...
Building application for the web...
Configuring `gql_build:schema_builder` in target `realspaceweb:realspaceweb` but this is not a known Builder
Configuring `gql_build:ast_builder` in target `realspaceweb:realspaceweb` but this is not a known Builder
Configuring `gql_build:op_builder` in target `realspaceweb:realspaceweb` but this is not a known Builder
Configuring `gql_build:data_builder` in target `realspaceweb:realspaceweb` but this is not a known Builder
Configuring `gql_build:var_builder` in target `realspaceweb:realspaceweb` but this is not a known Builder
Configuring `gql_build:fragment_builder` in target `realspaceweb:realspaceweb` but this is not a known Builder
Configuring `gql_client:req_builder` in target `realspaceweb:realspaceweb` but this is not a known Builder
Error creating realspaceweb|lib/widgets/search/SearchLocationButton.ddc.dill
Error creating kernel summary for module:realspaceweb|lib/widgets/search/SearchLocationButton.ddc.dill

Response:--dart-sdk-output=/private/var/folders/nr/yvt4wkdn3p9_dy_6b5bc3zxh0000gn/T/scratch_space0jEMkm/packages/realspaceweb/widgets/search/SearchLocationButton.ddc.dill --packages-file=file:///var/folders/nr/yvt4wkdn3p9_dy_6b5bc3zxh0000gn/T/kernel_builder_3SGhES/.packages --multi-root-scheme=org-dartlang-app --exclude-non-sources --summary-only --target=ddc --libraries-file=file:///Users/user/Dropbox/BUSINESS/Soft/flutter/bin/cache/flutter_web_sdk/libraries.json --reuse-compiler-result --use-incremental-compiler --used-inputs=/var/folders/nr/yvt4wkdn3p9_dy_6b5bc3zxh0000gn/T/kernel_builder_XAvEiZ/used_inputs.txt --input-summary=org-dartlang-app:///packages/expandable/expandable.ddc.dill --input-summary=org-dartlang-app:///packages/gql_client/gql_client.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/material.ddc.dill --input-summary=org-dartlang-app:///packages/font_awesome_flutter/font_awesome_flutter.ddc.dill --input-summary=org-dartlang-app:///packages/gql_http_link/gql_http_link.ddc.dill --input-summary=org-dartlang-app:///packages/normalize/normalize.ddc.dill --input-summary=org-dartlang-app:///packages/gql_exec/gql_exec.ddc.dill --input-summary=org-dartlang-app:///packages/meta/meta.ddc.dill --input-summary=org-dartlang-app:///packages/hive/hive.ddc.dill --input-summary=org-dartlang-app:///packages/built_value/built_value.ddc.dill --input-summary=org-dartlang-app:///packages/gql/ast.ddc.dill --input-summary=org-dartlang-app:///packages/rxdart/rxdart.ddc.dill --input-summary=org-dartlang-app:///packages/gql_link/gql_link.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/gestures.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/foundation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/cupertino.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/widgets.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/vector_math_64.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/semantics.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/rendering.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/animation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/painting.ddc.dill --input-summary=org-dartlang-app:///packages/font_awesome_flutter/icon_data.ddc.dill --input-summary=org-dartlang-app:///packages/http/http.ddc.dill --input-summary=org-dartlang-app:///packages/gql_exec/exec/response.ddc.dill --input-summary=org-dartlang-app:///packages/gql_exec/exec/context.ddc.dill --input-summary=org-dartlang-app:///packages/gql_exec/exec/request.ddc.dill --input-summary=org-dartlang-app:///packages/gql_exec/exec/error.ddc.dill --input-summary=org-dartlang-app:///packages/gql_exec/exec/operation.ddc.dill --input-summary=org-dartlang-app:///packages/crypto/crypto.ddc.dill --input-summary=org-dartlang-app:///packages/gql/src/ast/ast.ddc.dill --input-summary=org-dartlang-app:///packages/rxdart/transformers.ddc.dill --input-summary=org-dartlang-app:///packages/rxdart/src/streams/never.ddc.dill --input-summary=org-dartlang-app:///packages/gql/language.ddc.dill --input-summary=org-dartlang-app:///packages/collection/collection.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/gestures/arena.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/foundation/_bitfield_web.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/cupertino/action_sheet.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/widgets/actions.ddc.dill --input-summary=org-dartlang-app:///packages/vector_math/hash.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/semantics/binding.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/rendering/animated_size.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/animation/animation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/painting/_network_image_web.ddc.dill --input-summary=org-dartlang-app:///packages/http/src/base_client.ddc.dill --input-summary=org-dartlang-app:///packages/http_parser/http_parser.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_data.ddc.dill --input-summary=org-dartlang-app:///packages/convert/convert.ddc.dill --input-summary=org-dartlang-app:///packages/source_span/source_span.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/algorithms.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/utils.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/iterable_zip.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/comparators.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/priority_queue.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/canonicalized_map.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_buffers.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/physics.ddc.dill --input-summary=org-dartlang-app:///packages/pedantic/pedantic.ddc.dill --input-summary=org-dartlang-app:///packages/string_scanner/src/eager_span_scanner.ddc.dill --input-summary=org-dartlang-app:///packages/charcode/ascii.ddc.dill --input-summary=org-dartlang-app:///packages/path/path.ddc.dill --input-summary=org-dartlang-app:///packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill --input-summary=org-dartlang-app:///packages/charcode/charcode.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/physics/clamped_simulation.ddc.dill --input-summary=org-dartlang-app:///packages/charcode/html_entity.ddc.dill --source=package:realspaceweb/widgets/search/SearchLocationButton.dart
Crash when compiling package:realspaceweb/config/AppConfig.dart,
at character offset null:
Reference to root::package:gql_client/src/store//memory_store.dart is not bound to an AST node. A library was expected
#0      Reference.asLibrary (package:kernel/ast.dart:265:7)
#1      LibraryDependency.targetLibrary (package:kernel/ast.dart:642:57)
#2      SourceLoader.computeFullComponent (package:front_end/src/fasta/source/source_loader.dart:873:38)
#3      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:890:38)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:275:14)
<asynchronous suspension>
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#6      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:252:12)
#7      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:462:52)
<asynchronous suspension>
#8      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#16     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:156:20)
#17     computeKernel (file:///b/s/w/ir/cache/builder/src/third_party/dart/utils/bazel/kernel_worker.dart:320:10)
<asynchronous suspension>
#18     KernelWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/utils/bazel/kernel_worker.dart:69:26)
#19     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _runZoned (dart:async/zone.dart:1518:10)
#23     runZoned (dart:async/zone.dart:1465:12)
#24     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#25     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/utils/bazel/kernel_worker.dart:38:48)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

#0      Reference.asLibrary (package:kernel/ast.dart:265:7)
#1      LibraryDependency.targetLibrary (package:kernel/ast.dart:642:57)
#2      SourceLoader.computeFullComponent (package:front_end/src/fasta/source/source_loader.dart:873:38)
#3      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:890:38)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:275:14)
<asynchronous suspension>
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#6      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:252:12)
#7      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:462:52)
<asynchronous suspension>
#8      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#16     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:156:20)
#17     computeKernel (file:///b/s/w/ir/cache/builder/src/third_party/dart/utils/bazel/kernel_worker.dart:320:10)
<asynchronous suspension>
#18     KernelWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/utils/bazel/kernel_worker.dart:69:26)
#19     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _runZoned (dart:async/zone.dart:1518:10)
#23     runZoned (dart:async/zone.dart:1465:12)
#24     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#25     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/utils/bazel/kernel_worker.dart:38:48)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

AssetNotFoundException: realspaceweb|lib/widgets/search/SearchLocationButton.ddc.dill
Error compiling dartdevc module:realspaceweb|lib/widgets/search/SearchLocationButton.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --kernel --dart-sdk-dill --modules=amd --no-summarize -o packages/realspaceweb/widgets/search/SearchLocationButton.ddc.js --source-map --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino --summary=packages/flutter/material.ddc.dill=packages/flutter/material --summary=packages/realspaceweb/constants/constants.ddc.dill=packages/realspaceweb/constants/constants --summary=packages/gql_exec/exec/context.ddc.dill=packages/gql_exec/exec/context --summary=packages/gql_exec/exec/error.ddc.dill=packages/gql_exec/exec/error --summary=packages/gql_exec/exec/response.ddc.dill=packages/gql_exec/exec/response --summary=packages/path/path.ddc.dill=packages/path/path --summary=packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill=packages/term_glyph/src/generated/ascii_glyph_set --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/charcode/html_entity.ddc.dill=packages/charcode/html_entity --summary=packages/charcode/charcode.ddc.dill=packages/charcode/charcode --summary=packages/source_span/source_span.ddc.dill=packages/source_span/source_span --summary=packages/gql/src/ast/ast.ddc.dill=packages/gql/src/ast/ast --summary=packages/gql/ast.ddc.dill=packages/gql/ast --summary=packages/gql_exec/exec/operation.ddc.dill=packages/gql_exec/exec/operation --summary=packages/gql_exec/exec/request.ddc.dill=packages/gql_exec/exec/request --summary=packages/gql_exec/gql_exec.ddc.dill=packages/gql_exec/gql_exec --summary=packages/gql/language.ddc.dill=packages/gql/language --summary=packages/gql_link/gql_link.ddc.dill=packages/gql_link/gql_link --summary=packages/pedantic/pedantic.ddc.dill=packages/pedantic/pedantic --summary=packages/string_scanner/src/eager_span_scanner.ddc.dill=packages/string_scanner/src/eager_span_scanner --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/http_parser/http_parser.ddc.dill=packages/http_parser/http_parser --summary=packages/http/src/base_client.ddc.dill=packages/http/src/base_client --summary=packages/http/http.ddc.dill=packages/http/http --summary=packages/gql_http_link/gql_http_link.ddc.dill=packages/gql_http_link/gql_http_link --summary=packages/realspaceweb/widgets/search/SearchSectionTitle.ddc.dill=packages/realspaceweb/widgets/search/SearchSectionTitle --summary=packages/realspaceweb/widgets/search/SearchSection.ddc.dill=packages/realspaceweb/widgets/search/SearchSection --summary=packages/font_awesome_flutter/icon_data.ddc.dill=packages/font_awesome_flutter/icon_data --summary=packages/font_awesome_flutter/font_awesome_flutter.ddc.dill=packages/font_awesome_flutter/font_awesome_flutter --summary=packages/realspaceweb/utils/Utils.ddc.dill=packages/realspaceweb/utils/Utils --summary=packages/realspaceweb/config/AppConfig.ddc.dill=packages/realspaceweb/config/AppConfig --summary=packages/normalize/normalize.ddc.dill=packages/normalize/normalize --summary=packages/convert/convert.ddc.dill=packages/convert/convert --summary=packages/crypto/crypto.ddc.dill=packages/crypto/crypto --summary=packages/hive/hive.ddc.dill=packages/hive/hive --summary=packages/built_value/built_value.ddc.dill=packages/built_value/built_value --summary=packages/rxdart/src/streams/never.ddc.dill=packages/rxdart/src/streams/never --summary=packages/rxdart/transformers.ddc.dill=packages/rxdart/transformers --summary=packages/rxdart/rxdart.ddc.dill=packages/rxdart/rxdart --summary=packages/gql_client/gql_client.ddc.dill=packages/gql_client/gql_client --summary=packages/realspaceweb/widgets/DropdownStringWidget.ddc.dill=packages/realspaceweb/widgets/DropdownStringWidget --summary=packages/expandable/expandable.ddc.dill=packages/expandable/expandable --packages=file:///var/folders/nr/yvt4wkdn3p9_dy_6b5bc3zxh0000gn/T/kernel_builder_ptIly3/.packages --module-name=packages/realspaceweb/widgets/search/SearchLocationButton --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///Users/user/Dropbox/BUSINESS/Soft/flutter/bin/cache/flutter_web_sdk/libraries.json --used-inputs-file=/var/folders/nr/yvt4wkdn3p9_dy_6b5bc3zxh0000gn/T/ddk_builder_N3Q6uB/used_inputs.txt package:realspaceweb/widgets/search/SearchLocationButton.dart
    dart --version: 2.8.0-dev.0.0.flutter-c547f5d933 (Fri Dec 27 00:43:14 2019 +0000) on "macos_x64"

Crash when compiling null,
at character offset null:
Reference to root::package:gql_client/src/store//memory_store.dart is not bound to an AST node. A library was expected
#0      Reference.asLibrary (package:kernel/ast.dart:265:7)
#1      LibraryDependency.targetLibrary (package:kernel/ast.dart:642:57)
#2      SourceLoader.computeFullComponent (package:front_end/src/fasta/source/source_loader.dart:873:38)
#3      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:890:38)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:275:14)
<asynchronous suspension>
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#6      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:252:12)
#7      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:462:52)
<asynchronous suspension>
#8      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#16     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:156:20)
#17     _compile (package:dev_compiler/src/kernel/command.dart:333:64)
<asynchronous suspension>
#18     compile (package:dev_compiler/src/kernel/command.dart:46:18)
#19     compile (package:dev_compiler/src/compiler/shared_command.dart:410:10)
#20     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#21     _rootRun (dart:async/zone.dart:1126:13)
#22     _CustomZone.run (dart:async/zone.dart:1023:19)
#23     _runZoned (dart:async/zone.dart:1518:10)
#24     runZoned (dart:async/zone.dart:1465:12)
#25     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#26     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#27     _rootRun (dart:async/zone.dart:1126:13)
#28     _CustomZone.run (dart:async/zone.dart:1023:19)
#29     _runZoned (dart:async/zone.dart:1518:10)
#30     runZoned (dart:async/zone.dart:1465:12)
#31     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#32     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

#0      Reference.asLibrary (package:kernel/ast.dart:265:7)
#1      LibraryDependency.targetLibrary (package:kernel/ast.dart:642:57)
#2      SourceLoader.computeFullComponent (package:front_end/src/fasta/source/source_loader.dart:873:38)
#3      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:890:38)
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:275:14)
<asynchronous suspension>
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#6      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:252:12)
#7      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:462:52)
<asynchronous suspension>
#8      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#16     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:156:20)
#17     _compile (package:dev_compiler/src/kernel/command.dart:333:64)
<asynchronous suspension>
#18     compile (package:dev_compiler/src/kernel/command.dart:46:18)
#19     compile (package:dev_compiler/src/compiler/shared_command.dart:410:10)
#20     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#21     _rootRun (dart:async/zone.dart:1126:13)
#22     _CustomZone.run (dart:async/zone.dart:1023:19)
#23     _runZoned (dart:async/zone.dart:1518:10)
#24     runZoned (dart:async/zone.dart:1465:12)
#25     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#26     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#27     _rootRun (dart:async/zone.dart:1126:13)
#28     _CustomZone.run (dart:async/zone.dart:1023:19)
#29     _runZoned (dart:async/zone.dart:1518:10)
#30     runZoned (dart:async/zone.dart:1465:12)
#31     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#32     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

AssetNotFoundException: realspaceweb|lib/widgets/search/SearchLocationButton.ddc.dill

AssetNotFoundException: realspaceweb|lib/main_prod_web_entrypoint.ddc.js

AssetNotFoundException: realspaceweb|lib/widgets/search/SearchLocationButton.ddc.dill

AssetNotFoundException: realspaceweb|lib/widgets/search/SearchLocationButton.ddc.dill

AssetNotFoundException: realspaceweb|lib/widgets/search/SearchLocationButton.ddc.dill

AssetNotFoundException: realspaceweb|lib/main_web_entrypoint.ddc.js
Failed after 382ms
Finished with error: Failed to build application for the Web.

**Comment by smkhalsa** [comment]
Looks like the issue might have been here:

https://github.com/smkhalsa/gql_client/commit/a95803add3c52e90b7fa578e32773292dfc3d262#diff-850a1fee74177ca08bfec8af4bbea88fL5

Can you update to the latest version and try again?

**Comment by smkhalsa** [comment]
Closing for now. If this is still an issue, please let me know.

**Comment by smkhalsa** [comment]
Closing for now. If this is still an issue, please let me know.
